"""Compile a reviewed stage-CAD scene into a portable SDF mesh package."""

from __future__ import annotations

import csv
import math
import re
import shutil
import struct
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from .convex_collision import PartSettings, decompose_sources, part_settings_from_config
from .paths import CACHE_ROOT, EXPORT_ROOT, resolve_repo_path, review_artifact_stem

COLLISION_MODES = ("hull", "convex")


@dataclass
class LinkSpec:
    """One SDF rigid body and the globally positioned meshes rigidly attached to it."""

    name: str
    meshes: list[tuple[str, Path, list[float] | None]] = field(default_factory=list)


@dataclass(frozen=True)
class JointSpec:
    """A scalar joint expressed in the assembly frame at the reviewed home pose."""

    name: str
    stack: str
    reference: str
    joint_type: str
    parent: str
    child: str
    axis: list[float]
    origin: list[float]
    lower: float
    upper: float
    logical_home: float
    # Differs from logical_home only where the CAD pose is not the reviewed home.
    reviewed_home: float


def compile_sdf_package(
    scene_path: str | Path,
    output_dir: str | Path,
    *,
    model_name: str | None = None,
    include_collisions: bool = False,
    collision_mode: str = "hull",
    decomposition_workers: int | None = None,
    archive: bool = True,
) -> tuple[Path, Path | None]:
    """Compile one cached stage-CAD scene into SDF, binary STL, and MATLAB helpers."""

    if collision_mode not in COLLISION_MODES:
        raise ValueError(f"collision_mode must be one of {COLLISION_MODES}, got {collision_mode!r}")
    scene_file = Path(scene_path).resolve()
    scene = yaml.safe_load(scene_file.read_text(encoding="utf-8"))
    if not str(scene.get("schema", "")).startswith("slac-stage-cad-scene/"):
        raise ValueError(f"Expected a stage-CAD scene, got {scene.get('schema')!r}")

    package_dir = Path(output_dir).resolve()
    meshes_dir = package_dir / "meshes"
    if package_dir.exists():
        if not (package_dir / ".slac-sdf-package").exists():
            raise FileExistsError(
                f"Refusing to replace {package_dir}: it is not a generated SLAC SDF package"
            )
        shutil.rmtree(package_dir)
    meshes_dir.mkdir(parents=True)
    (package_dir / ".slac-sdf-package").write_text(
        "Generated by twin_lab.sdf_compiler.\n", encoding="utf-8"
    )

    resolved_model_name = _safe_name(model_name or _default_model_name(scene_file))
    links, joints = _build_tree(scene, scene_file)
    # The canonical SDF is Drake-first and must use OBJ visuals, because Drake's Meshcat
    # cannot render STL. MATLAB gets its own STL variant so both toolchains stay supported.
    matlab_collisions = include_collisions and collision_mode == "hull"
    visual_mesh_uris, stl_mesh_uris, drake_collision_uris = _convert_meshes(
        links,
        meshes_dir,
        scene_file,
        include_collision_obj=include_collisions,
        collision_mode=collision_mode,
        decomposition_workers=decomposition_workers,
        decomposition_settings=part_settings_from_config(_read_decomposition_config(scene)),
    )
    sdf_path = package_dir / f"{resolved_model_name}.sdf"
    _write_sdf(
        sdf_path,
        resolved_model_name,
        links,
        joints,
        visual_mesh_uris,
        collision_mesh_uris=drake_collision_uris,
        include_collisions=include_collisions,
        declare_convex=collision_mode == "convex",
    )
    matlab_sdf_name = f"{resolved_model_name}_matlab.sdf"
    _write_sdf(
        package_dir / matlab_sdf_name,
        resolved_model_name,
        links,
        joints,
        stl_mesh_uris,
        collision_mesh_uris={source: [("", uri)] for source, uri in stl_mesh_uris.items()},
        include_collisions=matlab_collisions,
        declare_convex=False,
    )
    _write_joint_metadata(package_dir / "joint_metadata.csv", joints)
    _write_matlab_loader(package_dir / "load_in_matlab.m", matlab_sdf_name)
    _write_package_readme(package_dir / "README.md", sdf_path.name, joints, include_collisions)

    archive_path = None
    if archive:
        archive_path = Path(
            shutil.make_archive(
                str(package_dir),
                "zip",
                root_dir=package_dir.parent,
                base_dir=package_dir.name,
            )
        )
    return sdf_path, archive_path


def _build_tree(scene: dict[str, Any], scene_file: Path) -> tuple[list[LinkSpec], list[JointSpec]]:
    base = LinkSpec("assembly_base")
    links = [base]
    joints: list[JointSpec] = []
    motion_meshes = scene["motion_stage_meshes"]

    for instance in scene["instances"]:
        if instance["ref"] not in motion_meshes:
            base.meshes.append(
                (
                    f"{instance['ref']}_{instance['model']}",
                    _resolve_path(instance["mesh"], scene_file),
                    [float(value) for value in instance.get("rgba", [0.62, 0.66, 0.72, 1.0])],
                )
            )

    for item in scene.get("static_geometry", []):
        base.meshes.append(
            (
                f"environment_{item['source_ref']}_{item['name']}",
                _resolve_path(item["mesh"], scene_file),
                [float(value) for value in item.get("rgba", [0.62, 0.66, 0.72, 1.0])],
            )
        )

    instance_by_ref = {str(item["ref"]): item for item in scene["instances"]}
    last_link_by_stage: dict[str, LinkSpec] = {}
    for chain in scene["motion_chains"]:
        parent = base
        stack_slug = _safe_name(chain["name"])
        for index, item in enumerate(chain["joints"], start=1):
            reference = str(item["ref"])
            fixed_role = item.get("fixed_role")
            if fixed_role:
                parent.meshes.append(
                    (
                        f"{reference}_{fixed_role}",
                        _resolve_path(motion_meshes[reference][fixed_role], scene_file),
                        [
                            float(value)
                            for value in instance_by_ref.get(reference, {}).get(
                                "rgba", [0.62, 0.66, 0.72, 1.0]
                            )
                        ],
                    )
                )

            axis_name = str(item["name"])
            child = LinkSpec(_safe_name(f"{stack_slug}_{index:02d}_{reference}_{axis_name}"))
            moving_role = str(item["moving_role"])
            child.meshes.append(
                (
                    f"{reference}_{moving_role}",
                    _resolve_path(motion_meshes[reference][moving_role], scene_file),
                    [
                        float(value)
                        for value in instance_by_ref.get(reference, {}).get(
                            "rgba", [0.62, 0.66, 0.72, 1.0]
                        )
                    ],
                )
            )
            links.append(child)

            home = float(item.get("home", 0.0))
            cad_position = float(item.get("cad_position", home))
            limits = [float(value) - cad_position for value in item["limits"]]
            joint_name = _safe_name(f"{stack_slug}_{reference}_{axis_name}")
            joints.append(
                JointSpec(
                    name=joint_name,
                    stack=str(chain["name"]),
                    reference=reference,
                    joint_type=str(item["joint_type"]),
                    parent=parent.name,
                    child=child.name,
                    axis=[float(value) for value in item["axis_world"]],
                    origin=[float(value) for value in item["origin_m"]],
                    lower=limits[0],
                    upper=limits[1],
                    logical_home=cad_position,
                    reviewed_home=home,
                )
            )
            parent = child
            last_link_by_stage[reference] = child

    for attachment in scene["attachments"]:
        parent_ref = attachment["parent_stage_ref"]
        target = base if parent_ref is None else last_link_by_stage[str(parent_ref)]
        label = "fixed_attachment" if parent_ref is None else f"{parent_ref}_attachment"
        target.meshes.append(
            (
                f"{label}_{attachment.get('style', 'default')}",
                _resolve_path(attachment["mesh"], scene_file),
                [float(value) for value in attachment.get("rgba", [0.62, 0.66, 0.72, 1.0])],
            )
        )

    return links, joints


def _read_decomposition_config(scene: dict[str, Any]) -> dict[str, Any] | None:
    """The reviewed inventory carries the per-part CoACD overrides, reachable via the scene."""

    inventory_path = scene.get("source_inventory")
    if not inventory_path:
        return None
    inventory = yaml.safe_load(resolve_repo_path(inventory_path).read_text(encoding="utf-8"))
    return (inventory or {}).get("decomposition")


def _convert_meshes(
    links: list[LinkSpec],
    meshes_dir: Path,
    scene_file: Path,
    *,
    include_collision_obj: bool,
    collision_mode: str = "hull",
    decomposition_workers: int | None = None,
    decomposition_settings: PartSettings | None = None,
) -> tuple[dict[Path, str], dict[Path, str], dict[Path, list[tuple[str, str]]]]:
    sources = {source for link in links for _, source, _ in link.meshes}
    visual_result: dict[Path, str] = {}
    stl_result: dict[Path, str] = {}
    collision_result: dict[Path, list[tuple[str, str]]] = {}
    used_names: set[str] = set()
    decomposed = {}
    if include_collision_obj and collision_mode == "convex":
        decomposed = decompose_sources(
            sources,
            CACHE_ROOT / "convex-collision" / scene_file.parent.name,
            decomposition_settings or PartSettings(),
            workers=decomposition_workers,
            progress=True,
        )
    for source in sorted(sources):
        base_name = _safe_name(source.stem)
        name = base_name
        number = 2
        while name in used_names:
            name = f"{base_name}_{number}"
            number += 1
        used_names.add(name)
        # Drake's Meshcat cannot render STL, so the canonical SDF points at OBJ visuals.
        visual_target = meshes_dir / f"{name}.obj"
        shutil.copy2(source, visual_target)
        visual_result[source] = f"meshes/{visual_target.name}"
        stl_target = meshes_dir / f"{name}.stl"
        _obj_to_binary_stl(source, stl_target)
        stl_result[source] = f"meshes/{stl_target.name}"
        if not include_collision_obj:
            continue
        if collision_mode == "convex":
            pieces = []
            for part in decomposed.get(source, []):
                part_slug = _safe_name(part.part_ref)
                for index, hull in enumerate(part.hulls):
                    hull_target = meshes_dir / f"{name}_{part_slug}_{index:03d}.obj"
                    shutil.copy2(hull, hull_target)
                    pieces.append((f"{part_slug}_{index:03d}", f"meshes/{hull_target.name}"))
            collision_result[source] = pieces
        else:
            collision_result[source] = [("", visual_result[source])]
    return visual_result, stl_result, collision_result


def _write_sdf(
    output: Path,
    model_name: str,
    links: list[LinkSpec],
    joints: list[JointSpec],
    visual_mesh_uris: dict[Path, str],
    *,
    collision_mesh_uris: dict[Path, list[tuple[str, str]]],
    include_collisions: bool,
    declare_convex: bool,
) -> None:
    sdf = ET.Element("sdf", {"version": "1.6"})
    model = ET.SubElement(sdf, "model", {"name": model_name})
    ET.SubElement(model, "static").text = "false"

    for link in links:
        link_element = ET.SubElement(model, "link", {"name": link.name})
        for index, (label, source, rgba) in enumerate(link.meshes, start=1):
            geometry_name = _safe_name(f"{label}_{index}")
            visual = ET.SubElement(link_element, "visual", {"name": f"{geometry_name}_visual"})
            _add_mesh_geometry(visual, visual_mesh_uris[source])
            material = ET.SubElement(visual, "material")
            ET.SubElement(material, "diffuse").text = _numbers(rgba or [0.62, 0.66, 0.72, 1.0])
            if not include_collisions:
                continue
            for suffix, uri in collision_mesh_uris[source]:
                piece_name = f"{geometry_name}_{suffix}" if suffix else geometry_name
                collision = ET.SubElement(
                    link_element,
                    "collision",
                    {"name": f"{piece_name}_collision"},
                )
                _add_mesh_geometry(collision, uri, declare_convex=declare_convex)

    model.append(
        ET.Comment(
            " Joint coordinates are relative to the reviewed CAD home pose. "
            "See joint_metadata.csv for logical display offsets. "
        )
    )
    base_joint = ET.SubElement(model, "joint", {"name": "assembly_base_to_world", "type": "fixed"})
    ET.SubElement(base_joint, "parent").text = "world"
    ET.SubElement(base_joint, "child").text = "assembly_base"
    for joint in joints:
        element = ET.SubElement(model, "joint", {"name": joint.name, "type": joint.joint_type})
        ET.SubElement(element, "parent").text = joint.parent
        ET.SubElement(element, "child").text = joint.child
        ET.SubElement(element, "pose").text = _numbers([*joint.origin, 0.0, 0.0, 0.0])
        axis = ET.SubElement(element, "axis")
        ET.SubElement(axis, "xyz").text = _numbers(joint.axis)
        limit = ET.SubElement(axis, "limit")
        ET.SubElement(limit, "lower").text = _number(joint.lower)
        ET.SubElement(limit, "upper").text = _number(joint.upper)

    ET.indent(sdf, space="  ")
    tree = ET.ElementTree(sdf)
    tree.write(output, encoding="utf-8", xml_declaration=True)


def _add_mesh_geometry(parent: ET.Element, uri: str, *, declare_convex: bool = False) -> None:
    geometry = ET.SubElement(parent, "geometry")
    mesh = ET.SubElement(geometry, "mesh")
    ET.SubElement(mesh, "uri").text = uri
    ET.SubElement(mesh, "scale").text = "1 1 1"
    if declare_convex:
        ET.SubElement(mesh, "drake:declare_convex")


def _obj_to_binary_stl(source: Path, output: Path) -> None:
    vertices: list[tuple[float, float, float]] = []
    faces: list[tuple[int, int, int]] = []
    for line in source.read_text(encoding="utf-8").splitlines():
        if line.startswith("v "):
            values = line.split()
            vertices.append((float(values[1]), float(values[2]), float(values[3])))
        elif line.startswith("f "):
            indices = [_obj_index(value, len(vertices)) for value in line.split()[1:]]
            for index in range(1, len(indices) - 1):
                faces.append((indices[0], indices[index], indices[index + 1]))

    header = f"Twin Lab: {source.name}".encode("ascii", errors="replace")[:80]
    with output.open("wb") as stream:
        stream.write(header.ljust(80, b"\0"))
        stream.write(struct.pack("<I", len(faces)))
        for face in faces:
            a, b, c = (vertices[index] for index in face)
            normal = _triangle_normal(a, b, c)
            stream.write(struct.pack("<12fH", *normal, *a, *b, *c, 0))


def _obj_index(value: str, vertex_count: int) -> int:
    index = int(value.split("/", maxsplit=1)[0])
    return index - 1 if index > 0 else vertex_count + index


def _triangle_normal(
    a: tuple[float, float, float],
    b: tuple[float, float, float],
    c: tuple[float, float, float],
) -> tuple[float, float, float]:
    ab = [b[index] - a[index] for index in range(3)]
    ac = [c[index] - a[index] for index in range(3)]
    cross = (
        ab[1] * ac[2] - ab[2] * ac[1],
        ab[2] * ac[0] - ab[0] * ac[2],
        ab[0] * ac[1] - ab[1] * ac[0],
    )
    norm = math.sqrt(sum(value * value for value in cross))
    return (0.0, 0.0, 0.0) if norm == 0.0 else tuple(value / norm for value in cross)


def _write_joint_metadata(output: Path, joints: list[JointSpec]) -> None:
    with output.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.writer(stream)
        writer.writerow(
            [
                "joint_name",
                "stack",
                "stage_ref",
                "type",
                "sdf_lower",
                "sdf_upper",
                "logical_home_offset",
                "reviewed_home",
                "units",
                "axis_x",
                "axis_y",
                "axis_z",
            ]
        )
        for joint in joints:
            unit = "m" if joint.joint_type == "prismatic" else "rad"
            writer.writerow(
                [
                    joint.name,
                    joint.stack,
                    joint.reference,
                    joint.joint_type,
                    _number(joint.lower),
                    _number(joint.upper),
                    _number(joint.logical_home),
                    _number(joint.reviewed_home),
                    unit,
                    *(_number(value) for value in joint.axis),
                ]
            )


def _write_matlab_loader(output: Path, sdf_name: str) -> None:
    output.write_text(
        "% Load the reviewed SLAC stage stack into Robotics System Toolbox.\n"
        "packageDir = fileparts(mfilename('fullpath'));\n"
        f"sdfFile = fullfile(packageDir, '{sdf_name}');\n"
        "robot = importrobot(sdfFile, 'DataFormat', 'row');\n"
        "robot.Gravity = [0 0 -9.80665];\n"
        "figure;\n"
        "show(robot, 'Visuals', 'on', 'Collisions', 'off');\n"
        "title('SLAC optics and polycapillary stage stacks');\n",
        encoding="utf-8",
    )


def _write_package_readme(
    output: Path, sdf_name: str, joints: list[JointSpec], include_collisions: bool
) -> None:
    offset_joints = [joint for joint in joints if joint.logical_home != 0.0]
    offset_text = (
        "\n".join(
            f"- `{joint.name}`: logical angle = SDF coordinate + "
            f"{math.degrees(joint.logical_home):g} degrees"
            for joint in offset_joints
        )
        or "- None"
    )
    if include_collisions:
        compatibility_text = (
            "The loader selects the matching `_matlab.sdf`, which uses STL for visual and "
            f"collision geometry. The canonical `{sdf_name}` remains Drake-first and uses OBJ "
            "collision meshes. This collision export is experimental because Drake convex-hulls "
            "OBJ meshes.\n\n"
        )
    else:
        compatibility_text = (
            f"The canonical `{sdf_name}` deliberately contains no collision geometry, so it "
            "loads efficiently in Drake. The matching `_matlab.sdf` carries the same visuals "
            "as STL for MATLAB.\n\n"
        )
    output.write_text(
        "# SLAC stage-stack SDF package\n\n"
        "This is a kinematic model compiled from the reviewed STEP assembly. Meshes are in "
        "metres: the canonical SDF references OBJ because Drake's Meshcat cannot render STL, "
        "and the `_matlab.sdf` variant references binary STL. All mesh paths are relative so "
        "the entire directory can be moved.\n\n"
        "## MATLAB Robotics System Toolbox\n\n"
        "Open this directory in MATLAB and run:\n\n"
        "```matlab\n"
        "load_in_matlab\n"
        "```\n\n"
        f"{compatibility_text}"
        "The SDF coordinate of every joint is zero at the reviewed CAD pose. Two rotary stages "
        "have nonzero logical display offsets:\n\n"
        f"{offset_text}\n\n"
        "See `joint_metadata.csv` for limits, axes, stage references, and offsets. Collision "
        "geometry is intentionally excluded from the normal share package until per-part convex "
        "decomposition and filtering are reviewed. Mass and inertia values are also omitted "
        "because they have not been measured.\n",
        encoding="utf-8",
    )


def _resolve_path(value: str, scene_file: Path) -> Path:
    path = Path(value)
    if path.is_absolute() and path.exists():
        return path
    candidates = [Path.cwd() / path, *(parent / path for parent in scene_file.parents)]
    match = next((candidate for candidate in candidates if candidate.exists()), None)
    if match is None:
        raise FileNotFoundError(f"Could not resolve mesh path {value!r} from {scene_file}")
    return match.resolve()


def _default_model_name(scene_file: Path) -> str:
    name = scene_file.parent.name.removesuffix(".stage-cad")
    normalized = name.replace("-", "_").lower()
    return name if normalized.endswith("stage_stack") else f"{name}_stage_stack"


def _safe_name(value: str) -> str:
    name = re.sub(r"[^A-Za-z0-9_]+", "_", value.strip()).strip("_").lower()
    return name or "unnamed"


def _number(value: float) -> str:
    return f"{value:.15g}"


def _numbers(values: list[float]) -> str:
    return " ".join(_number(value) for value in values)


def main() -> None:
    """Compile an inventory or prepared scene into a portable SDF ZIP package."""

    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", help="Stage inventory YAML or prepared stage-cad scene.yaml")
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--model-name")
    parser.add_argument(
        "--with-collisions",
        action="store_true",
        help="Export experimental detailed collision meshes (slower and convex-hulled in Drake)",
    )
    parser.add_argument(
        "--collision-mode",
        choices=COLLISION_MODES,
        default="hull",
        help="hull copies each part mesh; convex runs CoACD so Drake sees true concavity",
    )
    parser.add_argument("--no-zip", action="store_true", help="Do not create a shareable ZIP")
    parser.add_argument(
        "--decomposition-workers",
        type=int,
        default=None,
        help="Parallel CoACD workers for --collision-mode convex",
    )
    args = parser.parse_args()

    source = resolve_repo_path(args.source).resolve()
    source_data = yaml.safe_load(source.read_text(encoding="utf-8"))
    if str(source_data.get("schema", "")).startswith("slac-stage-inventory/"):
        from .stage_cad_viewer import prepare_stage_cad

        scene_path = prepare_stage_cad(source)
        package_stem = review_artifact_stem(source)
    else:
        scene_path = source
        package_stem = source.parent.name.removesuffix(".stage-cad")
    output_dir = args.output_dir or EXPORT_ROOT / f"{package_stem}.sdf-package"
    sdf_path, archive_path = compile_sdf_package(
        scene_path,
        output_dir,
        model_name=args.model_name,
        include_collisions=args.with_collisions,
        collision_mode=args.collision_mode,
        decomposition_workers=args.decomposition_workers,
        archive=not args.no_zip,
    )
    print(f"SDF package: {sdf_path.parent}")
    print(f"SDF model: {sdf_path}")
    if archive_path is not None:
        print(f"Shareable ZIP: {archive_path}")


if __name__ == "__main__":
    main()
